version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "9080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 2048M
        reservations:
          cpus: "0.20"
          memory: 512M
